name: Build Demo

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    run: |
      apt-get update && apt-get install -y cpio
    steps:
      - uses: actions/checkout@v1
      - uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.access_token }}
          BRANCH: gh-pages
          FOLDER: 'dist-docs'
          BUILD_SCRIPT: make -f Makefile build-example
